apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: elasticsearch-templates.frankkoornstra.nl
spec:
  group: frankkoornstra.nl
  version: v1alpha1
  scope: Namespaced
  preserveUnknownFields: false
  names:
    plural: elasticsearch-templates
    singular: elasticsearch-template
    kind: ElasticsearchTemplate
    categories: [elasticsearch]
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          required: [hosts, definition]
          properties:
            hosts:
              type: array
              description: List of hosts names which can include scheme, host name and port.
              items:
                type: string
                nullable: false
                pattern: "^\\S+$"
            definition:
              type: object
              description: A valid definition as described in the documentation of Elasticsearch
